app <- ShinyDriver$new("../")
app$snapshotInit("word_intrusion")

app$setInputs(intruder = "care")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "site")
app$setInputs(confirm = "click")
app$setInputs(intruder = "technolog")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "news")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "cultur")
app$setInputs(confirm = "click")
app$setInputs(intruder = "televis")
app$setInputs(confirm = "click")
app$setInputs(intruder = "campaign")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "group")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "web")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "care")
app$setInputs(confirm = "click")
app$setInputs(intruder = "campaign")
app$setInputs(confirm = "click")
app$setInputs(nextq = "click")
app$setInputs(intruder = "coverag")
app$setInputs(confirm = "click")
app$snapshot()
